name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  # This range is compatible with Flutter 3.19.x to 3.22.x, which typically use Dart 3.0.x - 3.4.x.
  # If your `flutter --version` shows a Dart version significantly different, let me know.
  sdk: '>=3.0.0 <4.0.0' # Broad Dart 3.x compatibility

dependencies:
  flutter:
    sdk: flutter

  # Adjusted versions based on pub's suggestion and web compatibility
  firebase_core: ^2.24.2   # Keeping this version
  firebase_auth: ^4.20.0   # Downgraded to be compatible with firebase_core ^2.24.2
  google_sign_in: ^6.1.6   # Keeping this version

  cupertino_icons: ^1.0.8

# Removed dependency_overrides as the direct version fix should resolve it.
# If you still get PromiseJsImpl errors AFTER this, we might revisit overrides.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png