// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android: return android;
      case TargetPlatform.iOS: return ios;
      default: throw UnsupportedError('Platform not supported');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhkq58D7C_b6ti6y67Viqdm5EeZf3cDeQ',
    appId: '1:379461892589:android:59ac0c9a92c39816034fe4',
    messagingSenderId: '379461892589', // project_number
    projectId: 'ai-designer-db0b8',
    storageBucket: 'ai-designer-db0b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    // Note: apiKey is often the same for iOS as Android in Firebase projects.
    // However, for iOS, the primary config is GoogleService-Info.plist.
    apiKey: 'AIzaSyDhkq58D7C_b6ti6y67Viqdm5EeZf3cDeQ',
    // Note: The iOS appId is typically in the format 1:project_number:ios:unique_id.
    // This specific google-services.json does not directly provide it.
    // It's usually found in GoogleService-Info.plist or generated by `flutterfire configure`.
    appId: '1:379461892589:ios:YOUR_IOS_UNIQUE_APP_ID', // Placeholder: You need to get this from GoogleService-Info.plist or Firebase Console
    messagingSenderId: '379461892589', // project_number
    projectId: 'ai-designer-db0b8',
    storageBucket: 'ai-designer-db0b8.firebasestorage.app',
    // This client ID is found in the google-services.json under client_type: 2 (iOS OAuth client)
    iosClientId: '379461892589-ooti6tip89k861gg29r4d22fo81jq31g.apps.googleusercontent.com',
    // This bundle ID is found in the google-services.json under ios_info
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    // Note: apiKey is often the same across platforms in Firebase projects.
    apiKey: 'AIzaSyD5tFbM2EOyNuCOhJNFuyDgJkfn68A67vg',
    // Note: The web appId is typically in the format 1:project_number:web:unique_id.
    // This specific google-services.json does not directly provide it.
    // You get this when you add a web app in the Firebase Console.
    appId: '1:379461892589:web:YOUR_WEB_UNIQUE_APP_ID', // Placeholder: You need to get this from Firebase Console
    messagingSenderId: '379461892589', // project_number
    projectId: 'ai-designer-db0b8',
    authDomain: 'ai-designer-db0b8.firebaseapp.com', // project_id.firebaseapp.com
    storageBucket: 'ai-designer-db0b8.firebasestorage.app',
    // Note: measurementId is for Google Analytics and is added when you enable Analytics for your web app.
    // It's not present in the provided google-services.json.
    measurementId: 'G-YOUR_MEASUREMENT_ID', // Placeholder: Get this from Firebase Console if using Analytics
  );
}